const samples = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris efficitur arcu eget tortor scelerisque, quis commodo ipsum bibendum. Nam dignissim tempus scelerisque. Vivamus sed dolor aliquam, venenatis enim ut, molestie est. Duis ullamcorper purus eu dictum semper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque arcu tortor, sodales et augue eget, aliquam luctus eros. Nam consectetur efficitur maximus. Pellentesque sed libero nec lacus tristique molestie at sed ligula. Vivamus accumsan dictum turpis, a molestie lacus vehicula non. Sed hendrerit non risus quis rutrum. Nam cursus, lacus sit amet elementum laoreet, diam velit convallis lacus, eu sagittis nisl quam et leo. Pellentesque vel ornare sem. Donec eu consequat erat. Aliquam eget nisl vel magna pharetra aliquam. Praesent varius suscipit bibendum. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt a erat sit amet egestas. Quisque vestibulum purus at nisl viverra porta. Suspendisse eget dictum libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices nunc nec cursus eleifend. Praesent sit amet risus nec urna mattis hendrerit non blandit metus. Nam fringilla ac tellus commodo venenatis. Sed sed sodales nulla. Quisque accumsan venenatis nibh in finibus. Maecenas tincidunt arcu semper, dapibus purus nec, accumsan sem. Duis finibus euismod mi, sit amet accumsan odio tempor vel. Phasellus magna mauris, pharetra vitae augue sed, laoreet semper purus. Aenean porta sit amet velit in consequat. Aliquam erat volutpat. Cras dolor neque, mattis ac viverra id, posuere eu sem. Cras non quam lectus. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque commodo ipsum sagittis consequat feugiat. Fusce laoreet venenatis nisi, id convallis nisi ullamcorper eu. Nullam tincidunt, leo id volutpat hendrerit, elit erat malesuada libero, quis consequat magna odio sed purus. Cras massa lacus, faucibus a laoreet ac, cursus sed leo. Sed ac libero vitae ipsum tempus tempor. Fusce feugiat at risus eu pretium. Aenean vel urna in ipsum ultricies semper sed non neque. Mauris cursus dapibus libero vel sollicitudin. Praesent feugiat, lorem ut tincidunt dapibus, dui sapien mattis purus, eget egestas nulla metus et nibh. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ac viverra lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque a quam vel lorem dapibus porttitor nec vel libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus placerat nisi ac mi iaculis, ut tincidunt diam dignissim. Vivamus varius pharetra eros, vitae rhoncus felis laoreet id. Morbi feugiat pellentesque lorem. Integer ut sollicitudin dui. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis vestibulum leo. Maecenas eu laoreet ipsum. Suspendisse eget lorem pretium, mollis purus sed, posuere magna. Nullam leo metus, molestie eget ipsum non, ultrices sodales lectus. Aenean quis libero tincidunt, gravida magna sed, eleifend ipsum. Curabitur rutrum placerat pharetra. Aliquam venenatis fringilla pulvinar. Aenean venenatis tellus at purus tempor sagittis. Aenean ac libero vitae velit elementum malesuada eget in tellus. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis vestibulum leo. Maecenas eu laoreet ipsum. Suspendisse eget lorem pretium, mollis purus sed, posuere magna. Nullam leo metus, molestie eget ipsum non, ultrices sodales lectus. Aenean quis libero tincidunt, gravida magna sed, eleifend ipsum. Curabitur rutrum placerat pharetra. Aliquam venenatis fringilla pulvinar. Aenean venenatis tellus at purus tempor sagittis. Aenean ac libero vitae velit elementum malesuada eget in tellus. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mattis odio vel mi malesuada, non malesuada ligula tempus. In sit amet porttitor elit, id accumsan ipsum. Mauris aliquet hendrerit libero. Aenean consectetur aliquet tellus a ultricies. Cras sit amet elit nec enim accumsan pellentesque in ac magna. Cras orci diam, porta sit amet sollicitudin ut, lobortis lacinia quam. Praesent consectetur tincidunt mauris in hendrerit. Aenean ultricies sagittis ultricies. Nam eu bibendum sapien. Morbi egestas pretium erat efficitur gravida. Sed feugiat, nulla ac varius blandit, magna neque dignissim purus, id viverra justo velit vel nibh. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porttitor enim sed interdum malesuada. Donec consequat urna eu tristique venenatis. In hac habitasse platea dictumst. Fusce ac varius tortor. Proin elementum nisi sit amet felis eleifend blandit. Nullam orci dui, finibus sit amet justo sit amet, consequat aliquet nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer eu auctor quam, non sagittis arcu. Vestibulum lacinia, odio at condimentum pellentesque, massa nulla interdum leo, quis tempor orci tortor sit amet nibh. Donec euismod erat eget lectus iaculis, eget consectetur sem ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper interdum iaculis. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque euismod, massa vel blandit consequat, justo nisl vestibulum magna, quis congue ligula tortor id massa. Aenean fermentum lobortis lorem, vitae dignissim magna dapibus ac. Duis elementum massa tellus, vel molestie neque porttitor vitae. Quisque cursus elit odio, a lacinia nisl maximus ut. Mauris sollicitudin elementum elit, vel eleifend magna accumsan a. Sed convallis ex leo, in lacinia mauris aliquet nec. Nam euismod sit amet purus ut fringilla. Aliquam egestas lorem ac rhoncus posuere. ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ipsum erat, sodales non pellentesque in, convallis vitae ligula. Curabitur pulvinar leo sed sapien rhoncus facilisis. Nunc porttitor sollicitudin dictum. Donec euismod mollis lacus, ut laoreet erat rutrum a. Aenean eleifend euismod commodo. Etiam sit amet neque vel neque tincidunt ornare. Nunc ultrices consequat lectus, ac faucibus felis efficitur quis. Sed ultrices commodo mi, non bibendum felis mattis nec. Vestibulum augue libero, eleifend ut libero ut, sollicitudin ultrices tortor. Nunc sit amet nibh sed nibh viverra rutrum sed ut lectus. Aenean fermentum risus urna, quis molestie velit malesuada eget. Sed tincidunt urna vitae diam convallis, a convallis ante mollis. Nullam id risus tincidunt, malesuada ex sed, mattis est. Sed ullamcorper ante vel rutrum semper. ",
];
// 10 * 3 = 30 paragraphs
export default (samples.concat(samples).concat(samples));